apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: community-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-db
  template:
    metadata:
      labels:
        app: community-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1q2w3e4r!!A"
            - name: MYSQL_DATABASE
              value: "edu_community"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
              name: mysql-init-config
          
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-init-config
          configMap:
            name: mysql-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: community-db