apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-be
  labels:
    app: community-be
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: community-be
  template:
    metadata:
      labels:
        app: community-be
    spec:
      containers:
        - name: be
          image: k1mwayne/k8s-community-be:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          
          volumeMounts:
            - mountPath: /usr/src/app/public/image  
              name: image-storage

          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_DATABASE
              value: "edu_community"
            - name: BACKEND_PORT
              value: "3000"
            - name: NODE_ENV
              value: "development"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db-password
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: session-secret
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"

      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: backend-image-pvc