apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-image-pvc
spec:
  accessModes:
    - ReadWriteOnce  # 하나의 노드에서 읽고 쓰기 가능
  resources:
    requests:
      storage: 5Gi   # 5기가 용량 할당 (필요에 따라 조절)